server:
  shutdown: graceful

spring:    
  application:    name: sample-bff
  profiles:
    active:
    - dev
    - log_default  #logging in default format
#    - log_container  #logging in json format
  security:    filter:      dispatcher-types:
        - async
        - error
        - request        
        - forward 

  jackson:
    property-naming-strategy: SNAKE_CASE
    
  lifecycle:
    timeout-per-shutdown-phase: 20s          
     
mybatis:
  type-aliases-package: com.example.bff.domain.model     
  configuration:
    map-underscore-to-camel-case: true    