server:
  shutdown: graceful

spring:    
  application:
    name: sample-bff
  profiles:
    active:
    - dev
    - log_default  #logging in default format
#    - log_container  #logging in json format
#    - xray  #X-Ray Enabled
  security:
    filter:
      dispatcher-types:
        - async
        - error
        - request        
        - forward 
  jackson:
    property-naming-strategy: SNAKE_CASE    
  lifecycle:
    timeout-per-shutdown-phase: 20s
# Servicet File Upload Max Size
  servlet:
    multipart:
      file-size-threshold: 512KB
      max-file-size: 3MB
      max-request-size: 10MB
# Virtual Thread                  
  threads:
    virtual:
      enabled: true       
  messages:
    basename: messages, messages-fw-common, messages-fw-web
    
mybatis:
  type-aliases-package: com.example.bff.domain.model, com.example.fw.web.token
  configuration:
    map-underscore-to-camel-case: true    

 
transaction-token:
  store-type: db
#  store-type: session 
  path-partterns: /**
#  exclude-path-patterns:

pagination:
#  max-page-size: 100    
#  default-page: 0
  default-page-size: 5

aws:
  xray:
    tracing-filter-name: sample-bff

# Tomcat Access Log
#logback:
#  access:
#    enabled: false