spring:    
  application:
    name: sample-bff
  profiles:
    active:
    - dev
    - log_default  #logging in default format
#    - log_container  #logging in json format
#    - xray  #X-Ray Enabled
  messages:
    basename: messages, messages-fw-common, messages-fw-web
  security:
    filter:
      dispatcher-types:
        - async
        - error
        - request        
        - forward 
  jackson:
    property-naming-strategy: SNAKE_CASE
# Resourceオブジェクトに存在しないフィールドがJSONに指定されていた場合、エラーとする
    deserialization:
      fail-on-unknown-properties: true
# Graceful Shutdown
  lifecycle:
    timeout-per-shutdown-phase: 20s
# Servicet File Upload Max Size
  servlet:
    multipart:
      file-size-threshold: 512KB
      max-file-size: 3MB
      max-request-size: 10MB
# Virtual Thread                  
  threads:
    virtual:
      enabled: true       

# Transaction Rollback
  transaction:
    rollback-on-commit-failure: true
# Dynamic Routing DataSource (disabled on Sample AP Default)
  datasource:
    dynamic-routing:
      enabled: false 
# HikariCP AutoCommit false
    hikari:
      auto-commit: false
# Dynamic Routing DataSource HikariCP AutoCommit false
    read:
      hikari:
        auto-commit: false
    write:
      hikari:
        auto-commit: false
# Spring Cloud for AWS Parameter Store Integration & Secrets Manager Integration
# Default Disabled For Local Development
  cloud:
    aws:
      parameterstore:
        enabled: false
      secretsmanager:
        enabled: false
  config:
    import: 
      - optional:aws-parameterstore:/config/common/;/config/${spring.application.name}/
      - optional:aws-secretsmanager:/secrets/database-secrets?prefix=spring.datasource.
      - optional:aws-secretsmanager:/secrets/database-secrets?prefix=spring.datasource.read.
      - optional:aws-secretsmanager:/secrets/database-secrets?prefix=spring.datasource.write.

# Spring Cloud for AWS Micrometer CloudWatch Metrics Integration Common Configuration
# Default Disabled For Local Development
management:
  cloudwatch:
    metrics:
      export:
        enabled: false
        namespace: ${spring.application.name}
        step: 10s

# Mybatis
mybatis:
  type-aliases-package: com.example.bff.domain.model, com.example.fw.web.token
  configuration:
    map-underscore-to-camel-case: true

# Spring Cloud Circuit Breaker TimeLimiter
resilience4j:
  timelimiter:
   configs:
     default:
       timeoutDuration: 3s

# Transaction Token Check 
transaction-token:
  store-type: db
#  store-type: session 
  path-partterns: /**
#  exclude-path-patterns:

# Pageation
pagination:
#  max-page-size: 100    
#  default-page: 0
  default-page-size: 5

# X-Ray SDK(not ADOT)
aws:
  xray:
    tracing-filter-name: ${spring.application.name}

# Tomcat Access Log
#logback:
#  access:
#    enabled: false