spring:    
  profiles:
    active:
    - dev
    - log_default  #logging in default format
#    - log_container  #logging in json format

  jackson:
    property-naming-strategy: SNAKE_CASE
    
    
mybatis:
  type-aliases-package: com.example.bff.domain.model     
  configuration:
    map-underscore-to-camel-case: true    