server:
  shutdown: graceful

spring:    
  # SpringSecurityのCsrfRequestDataValueProcessorの同名のBean（requestDataValueProcessor）を上書きするため設定
  main:
    allow-bean-definition-overriding: true
  application:    name: sample-bff
  profiles:
    active:
    - dev
    - log_default  #logging in default format
#    - log_container  #logging in json format
#    - xray  #X-Ray Enabled
  security:    filter:      dispatcher-types:
        - async
        - error
        - request        
        - forward 

  jackson:
    property-naming-strategy: SNAKE_CASE
    
  lifecycle:
    timeout-per-shutdown-phase: 20s          
     
mybatis:
  type-aliases-package: com.example.bff.domain.model     
  configuration:
    map-underscore-to-camel-case: true    


transaction:
  token:
    path-partterns=/**
#    exclude-path-patterns=    